export const Bot_JOB_TYPE = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  QUERY_REWARD: 'QUERY_REWARD',
  TIMED_TASK: 'TIMED_TASK',
  ONCE_TASK: 'ONCE_TASK',
  WEB_SOCKET_CONNECT: 'WEB_SOCKET_CONNECT'
}
